"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/** An abstract class which is used to read and construct
 * a tree from dictionary contents.
 *
 * Created by searene on 5/13/17.
 */
var StateMachine = (function () {
    function StateMachine(input) {
        // function name of the initial state
        this._initialState = 'initial';
        // function name of the completed state
        this._completedState = 'completed';
        this._input = input;
    }
    /** Run the state machine and get the result
     * generated by it.
     *
     * @returns {WordTree} result generated by the state machine
     */
    StateMachine.prototype.run = function () {
        // propel state machine
        var stateValue = { next: this.states[this._initialState] };
        while (stateValue.next != this.states[this._completedState]) {
            stateValue = stateValue.next(stateValue.param);
        }
        // state machine is completed, the generated tree
        // is stored in this._output, let's fetch it
        return this._wordTree;
    };
    return StateMachine;
}());
exports.StateMachine = StateMachine;
//# sourceMappingURL=StateMachine.js.map