/** An abstract class which is used to read and construct
 * a tree from dictionary contents.
 *
 * Created by searene on 5/13/17.
 */
export class StateMachine {
    constructor(input) {
        // function name of the initial state
        this._initialState = 'initial';
        // function name of the completed state
        this._completedState = 'completed';
        this._input = input;
    }
    /** Run the state machine and get the result
     * generated by it.
     *
     * @returns {WordTree} result generated by the state machine
     */
    run() {
        // propel state machine
        this.states[this._initialState]();
        // state machine is completed, the generated tree
        // is stored in this._output, let's fetch it
        return this._output;
    }
}
//# sourceMappingURL=StateMachine.js.map